apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: webapp:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: DATABASE_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: DATABASE_NAME

